[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
libfenix = { path = "../libfenix" }
include_dir = { path = "../include_dir" }

[build-dependencies]

[[bin]]
name = "kernel"
test = false
bench = false
