[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]

[build-dependencies]

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"

[[bin]]
name = "kernel"
test = false
bench = false
