[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
include_programs = { path = "../include_programs" }

[build-dependencies]

[[bin]]
name = "kernel"
test = false
bench = false
