[build]
target = "armv7a-none-eabi"

[target.armv7a-none-eabi]
linker = "arm-none-eabi-ld"
rustflags = [
    "-C", "link-arg=-Tboot/linker.ld",
    "-C", "link-arg=out/setup.o",
    "-C", "link-arg=out/exceptions.o",
    "-C", "link-arg=out/interrupts.o",
    "-C", "link-arg=out/software_interrupts.o",
    "-C", "link-arg=out/kernel.o",
    "-C", "link-arg=out/mmu.o",
]
