use crate::{peripherals::gpio::GpioPin, utils::wreg};

use super::gpio::{
    pins::{
        GPIO0_23, GPIO0_26, GPIO0_27, GPIO1_12, GPIO1_13, GPIO1_15, GPIO1_2, GPIO1_24, GPIO1_3,
        GPIO1_4, GPIO1_5, GPIO1_6, GPIO1_7, GPIO3_13,
    },
    GpioBank,
};

const CONTROL_MODULE_BASE: u32 = 0x44E10000;

pub fn mux_pin(pin: Pin, mode: u8, input: bool, pull_resistor: PullResistor) {
    let address = CONTROL_MODULE_BASE + pin.offset;
    wreg(
        address,
        mode as u32 & 0x7 | pull_resistor.to_mask() << 3 | (input as u32) << 5,
    );
}

pub struct Pin {
    offset: u32,
    pub pin0: PinType,
    pub pin1: PinType,
    pub pin2: PinType,
    pub pin3: PinType,
    pub pin4: PinType,
    pub pin5: PinType,
    pub pin6: PinType,
    pub pin7: PinType,
}

pub enum PinType {
    GpioPin(GpioPin),
    None,
}

pub enum PullResistor {
    None,
    PullDown,
    PullUp,
}

impl PullResistor {
    fn to_mask(&self) -> u32 {
        match self {
            PullResistor::PullDown => 0b00,
            PullResistor::PullUp => 0b10,
            PullResistor::None => 0b01,
        }
    }
}

const GPMC_AD0: Pin = Pin {
    offset: 0x800,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((0, GpioBank::Bank1)),
};
const GPMC_AD1: Pin = Pin {
    offset: 0x804,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((1, GpioBank::Bank1)),
};
const GPMC_AD2: Pin = Pin {
    offset: 0x808,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((2, GpioBank::Bank1)),
};
const GPMC_AD3: Pin = Pin {
    offset: 0x80C,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((3, GpioBank::Bank1)),
};
const GPMC_AD4: Pin = Pin {
    offset: 0x810,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((4, GpioBank::Bank1)),
};
const GPMC_AD5: Pin = Pin {
    offset: 0x814,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((5, GpioBank::Bank1)),
};
const GPMC_AD6: Pin = Pin {
    offset: 0x818,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((6, GpioBank::Bank1)),
};
const GPMC_AD7: Pin = Pin {
    offset: 0x81C,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((7, GpioBank::Bank1)),
};
const GPMC_AD8: Pin = Pin {
    offset: 0x820,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((22, GpioBank::Bank0)),
};
const GPMC_AD9: Pin = Pin {
    offset: 0x824,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((23, GpioBank::Bank0)),
};
const GPMC_AD10: Pin = Pin {
    offset: 0x828,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((26, GpioBank::Bank0)),
};
const GPMC_AD11: Pin = Pin {
    offset: 0x82C,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((27, GpioBank::Bank0)),
};
const GPMC_AD12: Pin = Pin {
    offset: 0x830,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((12, GpioBank::Bank1)),
};
const GPMC_AD13: Pin = Pin {
    offset: 0x834,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((13, GpioBank::Bank1)),
};
const GPMC_AD14: Pin = Pin {
    offset: 0x838,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((14, GpioBank::Bank1)),
};
const GPMC_AD15: Pin = Pin {
    offset: 0x83C,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((15, GpioBank::Bank1)),
};
const GPMC_A0: Pin = Pin {
    offset: 0x840,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((16, GpioBank::Bank1)),
};
const GPMC_A1: Pin = Pin {
    offset: 0x844,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((17, GpioBank::Bank1)),
};
const GPMC_A2: Pin = Pin {
    offset: 0x848,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((18, GpioBank::Bank1)),
};
const GPMC_A3: Pin = Pin {
    offset: 0x84C,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((19, GpioBank::Bank1)),
};
const GPMC_A4: Pin = Pin {
    offset: 0x850,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((20, GpioBank::Bank1)),
};
const GPMC_A5: Pin = Pin {
    offset: 0x854,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((21, GpioBank::Bank1)),
};
const GPMC_A6: Pin = Pin {
    offset: 0x858,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((22, GpioBank::Bank1)),
};
const GPMC_A7: Pin = Pin {
    offset: 0x85C,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((23, GpioBank::Bank1)),
};
const GPMC_A8: Pin = Pin {
    offset: 0x860,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((24, GpioBank::Bank1)),
};
const GPMC_A9: Pin = Pin {
    offset: 0x864,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((25, GpioBank::Bank1)),
};
const GPMC_A10: Pin = Pin {
    offset: 0x868,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((26, GpioBank::Bank1)),
};
const GPMC_A11: Pin = Pin {
    offset: 0x86C,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((27, GpioBank::Bank1)),
};
const GPMC_WAIT0: Pin = Pin {
    offset: 0x870,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((30, GpioBank::Bank0)),
};
const GPMC_WPN: Pin = Pin {
    offset: 0x874,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((31, GpioBank::Bank0)),
};
const GPMC_BEN1: Pin = Pin {
    offset: 0x878,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((28, GpioBank::Bank1)),
};
const GPMC_CSN0: Pin = Pin {
    offset: 0x87C,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((29, GpioBank::Bank1)),
};
const GPMC_CSN1: Pin = Pin {
    offset: 0x880,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((30, GpioBank::Bank1)),
};
const GPMC_CSN2: Pin = Pin {
    offset: 0x884,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((31, GpioBank::Bank1)),
};
const GPMC_CSN3: Pin = Pin {
    offset: 0x888,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((0, GpioBank::Bank2)),
};
const GPMC_CLK: Pin = Pin {
    offset: 0x88C,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((1, GpioBank::Bank2)),
};
const GPMC_ADVN_ALE: Pin = Pin {
    offset: 0x890,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((2, GpioBank::Bank2)),
};
const GPMC_OEN_REN: Pin = Pin {
    offset: 0x894,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((3, GpioBank::Bank2)),
};
const GPMC_WEN: Pin = Pin {
    offset: 0x898,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((4, GpioBank::Bank2)),
};
const GPMC_BEN0_CLE: Pin = Pin {
    offset: 0x89C,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((5, GpioBank::Bank2)),
};
const LCD_DATA0: Pin = Pin {
    offset: 0x8A0,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((6, GpioBank::Bank2)),
};
const LCD_DATA1: Pin = Pin {
    offset: 0x8A4,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((7, GpioBank::Bank2)),
};
const LCD_DATA2: Pin = Pin {
    offset: 0x8A8,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((8, GpioBank::Bank2)),
};
const LCD_DATA3: Pin = Pin {
    offset: 0x8AC,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((9, GpioBank::Bank2)),
};
const LCD_DATA4: Pin = Pin {
    offset: 0x8B0,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((10, GpioBank::Bank2)),
};
const LCD_DATA5: Pin = Pin {
    offset: 0x8B4,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((11, GpioBank::Bank2)),
};
const LCD_DATA6: Pin = Pin {
    offset: 0x8B8,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((12, GpioBank::Bank2)),
};
const LCD_DATA7: Pin = Pin {
    offset: 0x8BC,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((13, GpioBank::Bank2)),
};
const LCD_DATA8: Pin = Pin {
    offset: 0x8C0,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((14, GpioBank::Bank2)),
};
const LCD_DATA9: Pin = Pin {
    offset: 0x8C4,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((15, GpioBank::Bank2)),
};
const LCD_DATA10: Pin = Pin {
    offset: 0x8C8,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((16, GpioBank::Bank2)),
};
const LCD_DATA11: Pin = Pin {
    offset: 0x8CC,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((17, GpioBank::Bank2)),
};
const LCD_DATA12: Pin = Pin {
    offset: 0x8D0,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((8, GpioBank::Bank0)),
};
const LCD_DATA13: Pin = Pin {
    offset: 0x8D4,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((9, GpioBank::Bank0)),
};
const LCD_DATA14: Pin = Pin {
    offset: 0x8D8,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((10, GpioBank::Bank0)),
};
const LCD_DATA15: Pin = Pin {
    offset: 0x8DC,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((11, GpioBank::Bank0)),
};
const LCD_VSYNC: Pin = Pin {
    offset: 0x8E0,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((22, GpioBank::Bank2)),
};
const LCD_HSYNC: Pin = Pin {
    offset: 0x8E4,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((23, GpioBank::Bank2)),
};
const LCD_PCLK: Pin = Pin {
    offset: 0x8E8,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((24, GpioBank::Bank2)),
};
const LCD_AC_BIAS_EN: Pin = Pin {
    offset: 0x8EC,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((25, GpioBank::Bank2)),
};
const MMC0_DAT3: Pin = Pin {
    offset: 0x8F0,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((26, GpioBank::Bank2)),
};
const MMC0_DAT2: Pin = Pin {
    offset: 0x8F4,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((27, GpioBank::Bank2)),
};
const MMC0_DAT1: Pin = Pin {
    offset: 0x8F8,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((28, GpioBank::Bank2)),
};
const MMC0_DAT0: Pin = Pin {
    offset: 0x8FC,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((29, GpioBank::Bank2)),
};
const MMC0_CLK: Pin = Pin {
    offset: 0x900,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((30, GpioBank::Bank2)),
};
const MMC0_CMD: Pin = Pin {
    offset: 0x904,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((31, GpioBank::Bank2)),
};
const MII1_COL: Pin = Pin {
    offset: 0x908,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((0, GpioBank::Bank3)),
};
const MII1_CRS: Pin = Pin {
    offset: 0x90C,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((1, GpioBank::Bank3)),
};
const MII1_RX_ER: Pin = Pin {
    offset: 0x910,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((2, GpioBank::Bank3)),
};
const MII1_TX_EN: Pin = Pin {
    offset: 0x914,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((3, GpioBank::Bank3)),
};
const MII1_RX_DV: Pin = Pin {
    offset: 0x918,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((4, GpioBank::Bank3)),
};
const MII1_TXD3: Pin = Pin {
    offset: 0x91C,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((0, GpioBank::Bank0)),
};
const MII1_TXD2: Pin = Pin {
    offset: 0x920,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((17, GpioBank::Bank0)),
};
const MII1_TXD1: Pin = Pin {
    offset: 0x924,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((21, GpioBank::Bank0)),
};
const MII1_TXD0: Pin = Pin {
    offset: 0x928,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((28, GpioBank::Bank0)),
};
const MII1_TX_CLK: Pin = Pin {
    offset: 0x92C,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((9, GpioBank::Bank3)),
};
const MII1_RX_CLK: Pin = Pin {
    offset: 0x930,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((10, GpioBank::Bank3)),
};
const MII1_RXD3: Pin = Pin {
    offset: 0x934,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((18, GpioBank::Bank2)),
};
const MII1_RXD2: Pin = Pin {
    offset: 0x938,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((19, GpioBank::Bank2)),
};
const MII1_RXD1: Pin = Pin {
    offset: 0x93C,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((20, GpioBank::Bank2)),
};
const MII1_RXD0: Pin = Pin {
    offset: 0x940,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((21, GpioBank::Bank2)),
};
const RMII1_REF_CLK: Pin = Pin {
    offset: 0x944,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((29, GpioBank::Bank0)),
};
const MDIO_DATA: Pin = Pin {
    offset: 0x948,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((0, GpioBank::Bank0)),
};
const MDIO_CLK: Pin = Pin {
    offset: 0x94C,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((1, GpioBank::Bank0)),
};
const SPI0_SCLK: Pin = Pin {
    offset: 0x950,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((2, GpioBank::Bank0)),
};
const SPI0_D0: Pin = Pin {
    offset: 0x954,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((3, GpioBank::Bank0)),
};
const SPI0_D1: Pin = Pin {
    offset: 0x958,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((4, GpioBank::Bank0)),
};
const SPI0_CS0: Pin = Pin {
    offset: 0x95C,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((5, GpioBank::Bank0)),
};
const SPI0_CS1: Pin = Pin {
    offset: 0x960,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((6, GpioBank::Bank0)),
};
const ECAP0_IN_PWM0_OUT: Pin = Pin {
    offset: 0x964,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((7, GpioBank::Bank0)),
};
const UART0_CTSN: Pin = Pin {
    offset: 0x968,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((8, GpioBank::Bank1)),
};
const UART0_RTSN: Pin = Pin {
    offset: 0x96C,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((9, GpioBank::Bank1)),
};
const UART0_RXD: Pin = Pin {
    offset: 0x970,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((10, GpioBank::Bank1)),
};
const UART0_TXD: Pin = Pin {
    offset: 0x974,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((11, GpioBank::Bank1)),
};
const UART1_CTSN: Pin = Pin {
    offset: 0x978,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((12, GpioBank::Bank0)),
};
const UART1_RTSN: Pin = Pin {
    offset: 0x97C,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((13, GpioBank::Bank0)),
};
const UART1_RXD: Pin = Pin {
    offset: 0x980,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((14, GpioBank::Bank0)),
};
const UART1_TXD: Pin = Pin {
    offset: 0x984,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((15, GpioBank::Bank0)),
};
const I2C0_SDA: Pin = Pin {
    offset: 0x988,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((5, GpioBank::Bank3)),
};
const I2C0_SCL: Pin = Pin {
    offset: 0x98C,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((6, GpioBank::Bank3)),
};
const MCASP0_ACLKX: Pin = Pin {
    offset: 0x990,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((14, GpioBank::Bank3)),
};
const MCASP0_FSX: Pin = Pin {
    offset: 0x994,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((15, GpioBank::Bank3)),
};
const MCASP0_AXR0: Pin = Pin {
    offset: 0x998,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((16, GpioBank::Bank3)),
};
const MCASP0_AHCLKR: Pin = Pin {
    offset: 0x99C,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((17, GpioBank::Bank3)),
};
const MCASP0_ACLKR: Pin = Pin {
    offset: 0x9A0,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((18, GpioBank::Bank3)),
};
const MCASP0_FSR: Pin = Pin {
    offset: 0x9A4,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((19, GpioBank::Bank3)),
};
const MCASP0_AXR1: Pin = Pin {
    offset: 0x9A8,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((20, GpioBank::Bank3)),
};
const MCASP0_AHCLKX: Pin = Pin {
    offset: 0x9AC,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((21, GpioBank::Bank3)),
};
const XDMA_EVENT_INTR0: Pin = Pin {
    offset: 0x9B0,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((19, GpioBank::Bank0)),
};
const XDMA_EVENT_INTR1: Pin = Pin {
    offset: 0x9B4,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((20, GpioBank::Bank0)),
};
const WARMRSTN: Pin = Pin {
    offset: 0x9B8,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::None,
};
const NNMI: Pin = Pin {
    offset: 0x9C0,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::None,
};
const TMS: Pin = Pin {
    offset: 0x9D0,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::None,
};
const TDI: Pin = Pin {
    offset: 0x9D4,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::None,
};
const TDO: Pin = Pin {
    offset: 0x9D8,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::None,
};
const TCK: Pin = Pin {
    offset: 0x9DC,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::None,
};
const TRSTN: Pin = Pin {
    offset: 0x9E0,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::None,
};
const EMU0: Pin = Pin {
    offset: 0x9E4,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((7, GpioBank::Bank3)),
};
const EMU1: Pin = Pin {
    offset: 0x9E8,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((8, GpioBank::Bank3)),
};
const RTC_PWRONRSTN: Pin = Pin {
    offset: 0x9F8,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::None,
};
const PMIC_POWER_EN: Pin = Pin {
    offset: 0x9FC,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::None,
};
const EXT_WAKEUP: Pin = Pin {
    offset: 0xA00,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::None,
};
const USB0_DRVVBUS: Pin = Pin {
    offset: 0xA1C,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((18, GpioBank::Bank0)),
};
const USB1_DRVVBUS: Pin = Pin {
    offset: 0xA34,
    pin0: PinType::None,
    pin1: PinType::None,
    pin2: PinType::None,
    pin3: PinType::None,
    pin4: PinType::None,
    pin5: PinType::None,
    pin6: PinType::None,
    pin7: PinType::GpioPin((13, GpioBank::Bank3)),
};
